### ISSUE TITLE
a6300 hangs when using LiveView

### ISSUE THREAD

**Issue by dougforpres** [dougforpres/SonyCamera#3]
This only seems to affect a6300.
Camera functions fine until LiveView is started.

Typical flow for LiveView is:
1. GetSettings
2. Read preview "info"
3. Read preview "image"

Bug occurs after 1st image is read and it returns to step 1.  At this time camera hangs (according to windows) and after 5 mins error indicating device has hung is returned.
If code continues, the next frame is read, and it again hangs on the following step 1.

**Comment by dougforpres** [comment]
Another person with a6300 has offered to test - awaiting 👍 or 👎

**Comment by CopernicAI** [comment]
Hi there, I tested with a5000 . Nina throws the error, but APT surprisingly, connects without  a problem,just in live view mode instead of doing live mode it just taking non stop 2sec interval shots and taken photos presents as live view :) Plus, thank you for your outstanding work! 
clear skies from Lithuania,
reagards,
Minde

**Comment by dougforpres** [comment]
Thanks for the info - the problem seems limited to just the a6300 (where LiveView frames are supported by the camera and to the Sony remote software!  However, it only ever returns one to the driver then hangs).  The a5000 doesn't seem to support LiveView thru to the driver, so the driver just defaults to taking full-resolution photos.
